### ISSUE TITLE
Error: message=Location "=europe-west2-a" does not exist.

### ISSUE THREAD

**Issue by Ps3ud-0nym** [terraform-google-modules/terraform-google-kubernetes-engine#444]
Whenever I create a cluster and subsequently run a gcloud container command, I'm forced to append '--zone="location-name"' or '--location="location-name"

This is the full error I'm getting:

```
gcloud container clusters get-credentials my-k8s-cluster --verbosity=debug
DEBUG: Running [gcloud.container.clusters.get-credentials] with arguments: [--verbosity: "debug", NAME: "my-k8s-cluster"]
Fetching cluster endpoint and auth data.
DEBUG: (gcloud.container.clusters.get-credentials) ResponseError: code=400, message=Location "=europe-west2-a" does not exist.
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 795, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/container/clusters/get_credentials.py", line 102, in Run
    cluster = adapter.GetCluster(cluster_ref)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/api_lib/container/api_adapter.py", line 802, in GetCluster
    raise exceptions.HttpException(error, util.HTTP_ERROR_FORMAT)
HttpException: ResponseError: code=400, message=Location "=europe-west2-a" does not exist.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=400, message=Location "=europe-west2-a" does not exist.
```
And here is the same command working with '--zone="location-name"' appended:
```
gcloud container clusters get-credentials my-k8s-cluster --zone=europe-west2
Fetching cluster endpoint and auth data.
kubeconfig entry generated for my-k8s-cluster.
```

It seems the HTTP request isn't being formatted correctly for some reason. Here's my config below:

main.tf
```
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google"
  project_id                 = var.project_id
  region                     = var.region
  zones                      = var.zones
  name                       = var.name
  network                    = var.network
  subnetwork                 = var.subnetwork
  ip_range_pods              = ""
  ip_range_services          = ""
  http_load_balancing        = false
  horizontal_pod_autoscaling = true
  network_policy             = true
  create_service_account     = false
  remove_default_node_pool   = true
  monitoring_service         = "monitoring.googleapis.com/kubernetes"
  logging_service            = "logging.googleapis.com/kubernetes"

  node_pools = [
    {
      name                   = "my-node-pool"
      machine_type           = var.machine_type
      min_count              = var.min_count
      max_count              = var.max_count
      disk_size_gb           = var.disk_size_gb
      disk_type              = "pd-ssd"
      image_type             = "UBUNTU"
      auto_repair            = true
      auto_upgrade           = true
      service_account        = var.service_account
      preemptible            = false
      initial_node_count     = var.initial_node_count
    },
  ]

  node_pools_oauth_scopes = {

    all = []

    default-node-pool = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
  }


  node_pools_labels = {
    all = {}

    default-node-pool = {
      default-node-pool = true
    }
  }

  node_pools_metadata = {
    all = {}

    default-node-pool = {
      node-pool-metadata-custom-value = "my-node-pool"

    }
```
variables.auto.tf.vars
```
credentials        = "credentials.json"
project_id         = "my-kubernetes"
region             = "europe-west2"
zones              = ["europe-west2-a", "europe-west2-c"]
name               = "my-k8s-cluster"
machine_type       = "n1-standard-4"
min_count          = 1
max_count          = 4
disk_size_gb       = 120
service_account    = "my-k8s-service-account@my-kubernetes.iam.gserviceaccount.com"
initial_node_count = 1
network            = "my-k8s-vpc-network"
subnetwork         = "cluster-subnet"
pod_range          = "pod-subnet"
service_range      = "service-subnet"
~
~
```

**Comment by morgante** [comment]
This isn't related to the Terraform module and is expected behavior (you need to set `--location` argument on gcloud commands).

**Comment by Ps3ud-0nym** [comment]
Are you sure? In the past when I've created clusters with 'gcloud container clusters create' I don't recall having to append the location when running commands.

**Comment by morgante** [comment]
Perhaps the gcloud behavior has changed, but in either case the behavior is unrelated to this module.
